In [1]:
import pandas as pd
import numpy as np

In [18]:
dem = pd.read_excel('dem.xlsx', sheet_name='data-for-countries-etc-by-year')

In [19]:
dem = dem[dem['geo'] != 0]

In [20]:
dem['geo'] = list(map(lambda x : x.upper(), dem['geo']))

In [23]:
dem = dem[['geo', 'name', 'time', 'Democracy index (EIU)']]

In [24]:
dem = dem.rename(columns={'geo': 'index', 'name': 'Country', 'time': 'Time', 'Democracy index (EIU)': 'Democracy Score'})

In [26]:
table = dem.pivot_table('Democracy Score', ['index', 'Country'], 'Time')

In [28]:
table = table.reset_index()

In [30]:
table = table[['index', 'Country', 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019]]

In [32]:
table = table.rename(columns={2012: 'Dem Score 2012', 2013: 'Dem Score 2013', 2014: 'Dem Score 2014', 2015: 'Dem Score 2015', 2016: 'Dem Score 2016', 2017: 'Dem Score 2017', 2018: 'Dem Score 2018', 2019: 'Dem Score 2019'})

In [38]:
table.set_index('index').to_json('dem.json', orient='index')

In [39]:
combined = pd.read_json('../data/combined.json', orient='index')

In [40]:
combined

,Country,Region,CPI Score 2012,CPI Score 2013,CPI Score 2014,CPI Score 2015,CPI Score 2016,CPI Score 2017,CPI Score 2018,CPI Score 2019,...,EDU Score 2015,EDU Score 2016,EDU Score 2017,HDI Score 2012,HDI Score 2013,HDI Score 2014,HDI Score 2015,HDI Score 2016,HDI Score 2017,HDI Score 2018
NZL,New Zealand,AP,90.0,91.0,91.0,91.0,90.0,89,87,87,...,12.4,12.5,12.5,0.905,0.907,0.910,0.914,0.917,0.920,0.921
DNK,Denmark,WE/EU,90.0,91.0,92.0,91.0,90.0,88,88,87,...,12.5,12.6,12.6,0.924,0.926,0.928,0.926,0.928,0.929,0.930
FIN,Finland,WE/EU,90.0,89.0,89.0,90.0,89.0,85,85,86,...,12.4,12.4,12.4,0.908,0.916,0.918,0.919,0.922,0.924,0.925
CHE,Switzerland,WE/EU,86.0,85.0,86.0,86.0,86.0,85,85,85,...,13.4,13.4,13.4,0.935,0.938,0.939,0.943,0.943,0.943,0.946
SGP,Singapore,AP,87.0,86.0,84.0,85.0,84.0,84,85,85,...,11.5,11.5,11.5,0.920,0.923,0.928,0.929,0.933,0.934,0.935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AFG,Afghanistan,AP,8.0,8.0,12.0,11.0,15.0,15,16,16,...,3.6,3.6,3.8,0.479,0.485,0.488,0.490,0.491,0.493,0.496
YEM,Yemen,MENA,23.0,18.0,19.0,18.0,14.0,16,14,15,...,3.0,3.0,3.0,0.501,0.506,0.504,0.493,0.477,0.463,0.463
SYR,Syria,MENA,26.0,17.0,20.0,18.0,13.0,14,13,13,...,5.1,5.1,5.1,0.631,0.572,0.551,0.540,0.539,0.544,0.549
SSD,South Sudan,SSA,NaN,14.0,15.0,15.0,11.0,12,13,12,...,4.8,4.8,4.8,0.438,0.439,0.435,0.428,0.418,0.414,0.413
SOM,Somalia,SSA,8.0,8.0,8.0,8.0,10.0,9,10,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
combined = combined.reset_index()

In [43]:
combined = combined.merge(table, on='index', how='left')

In [45]:
del combined['Country_y']

In [46]:
combined = combined.rename(columns={'Country_x': 'Country'})

In [49]:
combined.set_index('index').to_json('combined.json', orient='index')